name: pytest
#on: [push,workflow_dispatch]
on: 
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
     # - name: clone repository
     #   run: |
      #    git clone https://github.com/xiaopeng163/github-actions-python
     #     cd github-actions-python
      - name: print github actions context
        run: echo ${{ github.repositoryUrl }}
      - name: pre checkout
        run: |
          pwd
          ls -lh
      - name: checkout code
        uses: actions/checkout@v4
      - name : post checkout
        run: |
          pwd
          ls -lh
      - name: install pytest11ddddddd
        run: pip install pytest
      - name: run pytest
        run: pytest
